package net.phazoganon.ostmusicdiscs.sound;

import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceKey;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.sounds.SoundEvent;
import net.minecraft.world.item.JukeboxSong;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.neoforge.registries.DeferredRegister;
import net.phazoganon.ostmusicdiscs.OSTMusicDiscs;

import java.util.function.Supplier;

public class ModSounds {
    public static final DeferredRegister<SoundEvent> SOUND_EVENTS = DeferredRegister.create(BuiltInRegistries.SOUND_EVENT, OSTMusicDiscs.MODID);
    public static final Supplier<SoundEvent> A_FAMILIAR_ROOM = registerSoundEvents("a_familiar_room");
    public static final ResourceKey<JukeboxSong> A_FAMILIAR_ROOM_KEY = createSong("a_familiar_room");
    public static final Supplier<SoundEvent> AERIE = registerSoundEvents("aerie");
    public static final ResourceKey<JukeboxSong> AERIE_KEY = createSong("aerie");
    public static final Supplier<SoundEvent> ALPHA = registerSoundEvents("alpha");
    public static final ResourceKey<JukeboxSong> ALPHA_KEY = createSong("alpha");
    public static final Supplier<SoundEvent> AN_ORDINARY_DAY = registerSoundEvents("an_ordinary_day");
    public static final ResourceKey<JukeboxSong> AN_ORDINARY_DAY_KEY = createSong("an_ordinary_day");
    public static final Supplier<SoundEvent> ANCESTRY = registerSoundEvents("ancestry");
    public static final ResourceKey<JukeboxSong> ANCESTRY_KEY = createSong("ancestry");
    public static final Supplier<SoundEvent> ARIA_MATH = registerSoundEvents("aria_math");
    public static final ResourceKey<JukeboxSong> ARIA_MATH_KEY = createSong("aria_math");
    public static final Supplier<SoundEvent> AXOLOTL = registerSoundEvents("axolotl");
    public static final ResourceKey<JukeboxSong> AXOLOTL_KEY = createSong("axolotl");
    public static final Supplier<SoundEvent> BALLAD_OF_THE_CATS = registerSoundEvents("ballad_of_the_cats");
    public static final ResourceKey<JukeboxSong> BALLAD_OF_THE_CATS_KEY = createSong("ballad_of_the_cats");
    public static final Supplier<SoundEvent> BEGINNING_2 = registerSoundEvents("beginning_2");
    public static final ResourceKey<JukeboxSong> BEGINNING_2_KEY = createSong("beginning_2");
    public static final Supplier<SoundEvent> BIOME_FEST = registerSoundEvents("biome_fest");
    public static final ResourceKey<JukeboxSong> BIOME_FEST_KEY = createSong("biome_fest_key");
    public static final Supplier<SoundEvent> BLIND_SPOTS = registerSoundEvents("blind_spots");
    public static final ResourceKey<JukeboxSong> BLIND_SPOTS_KEY = createSong("blind_spots");
    public static final Supplier<SoundEvent> BOSS = registerSoundEvents("boss");
    public static final ResourceKey<JukeboxSong> BOSS_KEY = createSong("boss");
    public static final Supplier<SoundEvent> BROMELIAD = registerSoundEvents("bromeliad");
    public static final ResourceKey<JukeboxSong> BROMELIAD_KEY = createSong("bromeliad");
    public static final Supplier<SoundEvent> CHRYSOPOEIA = registerSoundEvents("chrysopoeia");
    public static final ResourceKey<JukeboxSong> CHRYSOPOEIA_KEY = createSong("chrysopoeia");
    public static final Supplier<SoundEvent> CLARK = registerSoundEvents("clark");
    public static final ResourceKey<JukeboxSong> CLARK_KEY = createSong("clark");
    public static final Supplier<SoundEvent> COMFORTING_MEMORIES = registerSoundEvents("comforting_memories");
    public static final ResourceKey<JukeboxSong> COMFORTING_MEMORIES_KEY = createSong("comforting_memories");
    public static final Supplier<SoundEvent> CONCRETE_HALLS = registerSoundEvents("concrete_halls");
    public static final ResourceKey<JukeboxSong> CONCRETE_HALLS_KEY = createSong("concrete_halls");
    public static final Supplier<SoundEvent> CRESCENT_DUNES = registerSoundEvents("crescent_dunes");
    public static final ResourceKey<JukeboxSong> CRESCENT_DUNES_KEY = createSong("crescent_dunes");
    public static final Supplier<SoundEvent> DANNY = registerSoundEvents("danny");
    public static final ResourceKey<JukeboxSong> DANNY_KEY = createSong("danny");
    public static final Supplier<SoundEvent> DEAD_VOXEL = registerSoundEvents("dead_voxel");
    public static final ResourceKey<JukeboxSong> DEAD_VOXEL_KEY = createSong("dead_voxel");
    public static final Supplier<SoundEvent> DEEPER = registerSoundEvents("deeper");
    public static final ResourceKey<JukeboxSong> DEEPER_KEY = createSong("deeper");
    public static final Supplier<SoundEvent> DRAGON_FISH = registerSoundEvents("dragon_fish");
    public static final ResourceKey<JukeboxSong> DRAGON_FISH_KEY = createSong("dragon_fish");
    public static final Supplier<SoundEvent> DREITON = registerSoundEvents("dreiton");
    public static final ResourceKey<JukeboxSong> DREITON_KEY = createSong("dreiton");
    public static final Supplier<SoundEvent> DRY_HANDS = registerSoundEvents("dry_hands");
    public static final ResourceKey<JukeboxSong> DRY_HANDS_KEY = createSong("dry_hands");
    public static final Supplier<SoundEvent> ECHO_IN_THE_WIND = registerSoundEvents("echo_in_the_wind");
    public static final ResourceKey<JukeboxSong> ECHO_IN_THE_WIND_KEY = createSong("echo_in_the_wind");
    public static final Supplier<SoundEvent> ELD_UNKNOWN = registerSoundEvents("eld_unknown");
    public static final ResourceKey<JukeboxSong> ELD_UNKNOWN_KEY = createSong("eld_unknown");
    public static final Supplier<SoundEvent> ENDLESS = registerSoundEvents("endless");
    public static final ResourceKey<JukeboxSong> ENDLESS_KEY = createSong("endless");
    public static final Supplier<SoundEvent> FEATHERFALL = registerSoundEvents("featherfall");
    public static final ResourceKey<JukeboxSong> FEATHERFALL_KEY = createSong("featherfall");
    public static final Supplier<SoundEvent> FIREBUGS = registerSoundEvents("firebugs");
    public static final ResourceKey<JukeboxSong> FIREBUGS_KEY = createSong("firebugs");
    public static final Supplier<SoundEvent> FLOATING_DREAM = registerSoundEvents("floating_dream");
    public static final ResourceKey<JukeboxSong> FLOATING_DREAM_KEY = createSong("floating_dream");
    public static final Supplier<SoundEvent> FLOATING_TREES = registerSoundEvents("floating_trees");
    public static final ResourceKey<JukeboxSong> FLOATING_TREES_KEY = createSong("floating_trees");
    public static final Supplier<SoundEvent> HAGGSTROM = registerSoundEvents("haggstrom");
    public static final ResourceKey<JukeboxSong> HAGGSTROM_KEY = createSong("haggstrom");
    public static final Supplier<SoundEvent> HAUNT_MUSKIE = registerSoundEvents("haunt_muskie");
    public static final ResourceKey<JukeboxSong> HAUNT_MUSKIE_KEY = createSong("haunt_muskie");
    public static final Supplier<SoundEvent> INFINITE_AMETHYST = registerSoundEvents("infinite_amethyst");
    public static final ResourceKey<JukeboxSong> INFINITE_AMETHYST_KEY = createSong("infinite_amethyst");
    public static final Supplier<SoundEvent> KEY = registerSoundEvents("key");
    public static final ResourceKey<JukeboxSong> KEY_KEY = createSong("key");
    public static final Supplier<SoundEvent> KOMOREBI = registerSoundEvents("komorebi");
    public static final ResourceKey<JukeboxSong> KOMOREBI_KEY = createSong("komorebi");
    public static final Supplier<SoundEvent> LABYRINTHINE = registerSoundEvents("labyrinthine");
    public static final ResourceKey<JukeboxSong> LABYRINTHINE_KEY = createSong("labyrinthine");
    public static final Supplier<SoundEvent> LEFT_TO_BLOOM = registerSoundEvents("left_to_bloom");
    public static final ResourceKey<JukeboxSong> LEFT_TO_BLOOM_KEY = createSong("left_to_bloom");
    public static final Supplier<SoundEvent> LIVING_MICE = registerSoundEvents("living_mice");
    public static final ResourceKey<JukeboxSong> LIVING_MICE_KEY = createSong("living_mice");
    public static final Supplier<SoundEvent> MICE_ON_VENUS = registerSoundEvents("mice_on_venus");
    public static final ResourceKey<JukeboxSong> MICE_ON_VENUS_KEY = createSong("mice_on_venus");
    public static final Supplier<SoundEvent> MINECRAFT = registerSoundEvents("minecraft");
    public static final ResourceKey<JukeboxSong> MINECRAFT_KEY = createSong("minecraft");
    public static final Supplier<SoundEvent> MOOG_CITY_2 = registerSoundEvents("moog_city_2");
    public static final ResourceKey<JukeboxSong> MOOG_CITY_2_KEY = createSong("moog_city_2");
    public static final Supplier<SoundEvent> MUTATION = registerSoundEvents("mutation");
    public static final ResourceKey<JukeboxSong> MUTATION_KEY = createSong("mutation");
    public static final Supplier<SoundEvent> ONE_MORE_DAY = registerSoundEvents("one_more_day");
    public static final ResourceKey<JukeboxSong> ONE_MORE_DAY_KEY = createSong("one_more_day");
    public static final Supplier<SoundEvent> OXYGENE = registerSoundEvents("oxygene");
    public static final ResourceKey<JukeboxSong> OXYGENE_KEY = createSong("oxygene");
    public static final Supplier<SoundEvent> POKOPOKO = registerSoundEvents("pokopoko");
    public static final ResourceKey<JukeboxSong> POKOPOKO_KEY = createSong("pokopoko");
    public static final Supplier<SoundEvent> PUZZLEBOX = registerSoundEvents("puzzlebox");
    public static final ResourceKey<JukeboxSong> PUZZLEBOX_KEY = createSong("puzzlebox");
    public static final Supplier<SoundEvent> RUBEDO = registerSoundEvents("rubedo");
    public static final ResourceKey<JukeboxSong> RUBEDO_KEY = createSong("rubedo");
    public static final Supplier<SoundEvent> SHUNIJI = registerSoundEvents("shuniji");
    public static final ResourceKey<JukeboxSong> SHUNIJI_KEY = createSong("shuniji");
    public static final Supplier<SoundEvent> SO_BELOW = registerSoundEvents("so_below");
    public static final ResourceKey<JukeboxSong> SO_BELOW_KEY = createSong("so_below");
    public static final Supplier<SoundEvent> STAND_TALL = registerSoundEvents("stand_tall");
    public static final ResourceKey<JukeboxSong> STAND_TALL_KEY = createSong("stand_tall");
    public static final Supplier<SoundEvent> SUBWOOFER_LULLABY = registerSoundEvents("subwoofer_lullaby");
    public static final ResourceKey<JukeboxSong> SUBWOOFER_LULLABY_KEY = createSong("subwoofer_lullaby");
    public static final Supplier<SoundEvent> SWEDEN = registerSoundEvents("sweden");
    public static final ResourceKey<JukeboxSong> SWEDEN_KEY = createSong("sweden");
    public static final Supplier<SoundEvent> TASWELL = registerSoundEvents("taswell");
    public static final ResourceKey<JukeboxSong> TASWELL_KEY = createSong("taswell");
    public static final Supplier<SoundEvent> THE_END = registerSoundEvents("the_end");
    public static final ResourceKey<JukeboxSong> THE_END_KEY = createSong("the_end");
    public static final Supplier<SoundEvent> WARMTH = registerSoundEvents("warmth");
    public static final ResourceKey<JukeboxSong> WARMTH_KEY = createSong("warmth");
    public static final Supplier<SoundEvent> WENDING = registerSoundEvents("wending");
    public static final ResourceKey<JukeboxSong> WENDING_KEY = createSong("wending");
    public static final Supplier<SoundEvent> WET_HANDS = registerSoundEvents("wet_hands");
    public static final ResourceKey<JukeboxSong> WET_HANDS_KEY = createSong("wet_hands");
    public static final Supplier<SoundEvent> YAKUSOKU = registerSoundEvents("yakusoku");
    public static final ResourceKey<JukeboxSong> YAKUSOKU_KEY = createSong("yakusoku");
    private static ResourceKey<JukeboxSong> createSong(String name) {
        return ResourceKey.create(Registries.JUKEBOX_SONG, ResourceLocation.fromNamespaceAndPath(OSTMusicDiscs.MODID, name));
    }
    private static Supplier<SoundEvent> registerSoundEvents(String name) {
        return SOUND_EVENTS.register(name, () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath(OSTMusicDiscs.MODID, name)));
    }
    public static void register(IEventBus eventBus) {
        SOUND_EVENTS.register(eventBus);
    }
}